name: MLB HR Predictor Schedule

on:
  schedule:
    # Early morning run with probable pitchers
    - cron: '0 6 * * *'  # 6:00 AM daily
    # Lineup check runs throughout the day
    - cron: '0 10,13,16,19 * * *'  # 10AM, 1PM, 4PM, 7PM daily
  workflow_dispatch:  # Manual trigger option

jobs:
  run-predictor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run MLB HR Predictor
        run: python run_predictor.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          
      - name: Commit tracking changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add game_tracking.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update game tracking data"
          git push
